site_name: My Docs
site_url: https://my-website/doc/ 

theme:
  name: "material"
  custom_dir: overrides

nav:
  - index.md

markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
      #base_path: $relative

extra:
  version:
    provider: mike